.TH "Defines.h" 3 "Sat Sep 5 2015" "Version 1.0" "Stack_Machine_Dual_Operand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Defines.h \- 
.PP
Definição de valores fixos do sistema\&.  

.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSIZE\fP   256"
.br
.RI "\fIData size\&. \fP"
.ti -1c
.RI "#define \fBDATA_WIDTH\fP   32"
.br
.RI "\fITamanho da palavra do sistema\&. \fP"
.ti -1c
.RI "#define \fBRAM_DEPTH\fP   100"
.br
.RI "\fITamanho da memória RAM\&. \fP"
.ti -1c
.RI "#define \fBROM_DEPTH\fP   100"
.br
.RI "\fITamanho da memória ROM\&. \fP"
.ti -1c
.RI "#define \fBSTACK_SIZE\fP   16"
.br
.RI "\fITamanho máximo de pilha suportado\&. \fP"
.ti -1c
.RI "#define \fBDS_SIZE\fP   8"
.br
.RI "\fITamanho atual da pilha de dados\&. \fP"
.ti -1c
.RI "#define \fBRS_SIZE\fP   8"
.br
.RI "\fITamanho atual da pilha de retorno\&. \fP"
.ti -1c
.RI "#define \fBPATH\fP   '/home/nuts/Desktop/program\&.sm'"
.br
.RI "\fICaminho para o arquivo de programa\&. \fP"
.in -1c
.SH "Detailed Description"
.PP 
Definição de valores fixos do sistema\&. 


.PP
\fBAuthor:\fP
.RS 4
Gerson Miguel Beckenkamp 
.RE
.PP
\fBDate:\fP
.RS 4
2015/09/05 14:16:20 
.RE
.PP

.PP
Definition in file \fBDefines\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Stack_Machine_Dual_Operand from the source code\&.
