.TH "DSController" 3 "Sat Sep 5 2015" "Version 1.0" "Stack_Machine_Dual_Operand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DSController \- 
.PP
Controlador da pilha de dados\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DSController\&.h>\fP
.PP
Inherits sc_module\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBb_transport\fP (tlm::tlm_generic_payload &trans, sc_time &delay)"
.br
.ti -1c
.RI "\fB~DSController\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Controlador da pilha de dados\&. 

Módulo responsável por determinar quais operandos devem ser carregados da pilha de dados e obter estes operandos da mesma\&.
.PP
\fBAuthor:\fP
.RS 4
Gerson Miguel Beckenkamp 
.RE
.PP
\fBDate:\fP
.RS 4
2015/09/05 14:16:20 
.RE
.PP

.PP
Definition at line 34 of file DSController\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DSController::~DSController ()"
Destrutor do módulo\&. 
.PP
Definition at line 247 of file DSController\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void DSController::b_transport (tlm::tlm_generic_payload &trans, sc_time &delay)\fC [virtual]\fP"
Socket responsável por receber a instrução carregada pelo \fBFetch\fP\&. 
.PP
\fBParameters:\fP
.RS 4
\fItrans\fP Payload contendo os dados do pacote recebido\&. 
.br
\fIdelay\fP Timeout para a condirmação do comando recebido\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Não há retorno\&. 
.RE
.PP

.PP
Definition at line 28 of file DSController\&.cpp\&.
.PP
References SIZE\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stack_Machine_Dual_Operand from the source code\&.
