.TH "FileHandler.cpp" 3 "Sat Sep 5 2015" "Version 1.0" "Stack_Machine_Dual_Operand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileHandler.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'systemc'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <bitset>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileHandler\fP"
.br
.RI "\fIGerenciador de arquivos\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Stack_Machine_Dual_Operand from the source code\&.
