.TH "Ram" 3 "Sat Sep 5 2015" "Version 1.0" "Stack_Machine_Dual_Operand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ram \- 
.PP
Random Access Memory\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Ram\&.h>\fP
.PP
Inherits sc_module\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBb_transport\fP (tlm::tlm_generic_payload &trans, sc_time &delay)"
.br
.ti -1c
.RI "void \fBsetCnt\fP (int *cnt)"
.br
.ti -1c
.RI "\fB~Ram\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Random Access Memory\&. 

Módulo responsável por manter e fazer a interface entre a memória RAM com os demais módulos\&.
.PP
\fBAuthor:\fP
.RS 4
Gerson Miguel Beckenkamp 
.RE
.PP
\fBDate:\fP
.RS 4
2015/09/05 14:16:20 
.RE
.PP

.PP
Definition at line 24 of file Ram\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Ram::~Ram ()"
Destrutor do módulo\&. 
.PP
Definition at line 87 of file Ram\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void Ram::b_transport (tlm::tlm_generic_payload &trans, sc_time &delay)\fC [virtual]\fP"
Socket responsável por receber requerimentos da \fBAlu\fP, tanto para leituras quanto para escrita\&.
.PP
\fBParameters:\fP
.RS 4
\fItrans\fP Payload contendo os dados do pacote recebido\&. 
.br
\fIdelay\fP Timeout para a condirmação do comando recebido\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Não há retorno\&. 
.RE
.PP

.PP
Definition at line 26 of file Ram\&.cpp\&.
.PP
References SIZE\&.
.SS "void Ram::setCnt (int *cnt)"
Inicia o contador de acessos a memória\&. 
.PP
\fBParameters:\fP
.RS 4
\fIcnt\fP Ponteiro para contador de acessos a memória\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Não há retorno\&. 
.RE
.PP

.PP
Definition at line 80 of file Ram\&.cpp\&.
.PP
Referenced by SC_MODULE()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stack_Machine_Dual_Operand from the source code\&.
