.TH "Rom" 3 "Sat Sep 5 2015" "Version 1.0" "Stack_Machine_Dual_Operand" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Rom \- 
.PP
Read-Only Memory\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Rom\&.h>\fP
.PP
Inherits sc_module\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~Rom\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Read-Only Memory\&. 

Módulo responsável por manter e fazer a interface entre a memória ROM com os demais módulos\&.
.PP
\fBAuthor:\fP
.RS 4
Gerson Miguel Beckenkamp 
.RE
.PP
\fBDate:\fP
.RS 4
2015/09/05 14:16:20 
.RE
.PP

.PP
Definition at line 32 of file Rom\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Rom::~Rom ()"
Destrutor do módulo\&. 
.PP
Definition at line 71 of file Rom\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Stack_Machine_Dual_Operand from the source code\&.
