StackMachineDualOperand: DSController Class Reference
DSController Class Reference
Controlador da pilha de dados.
#include <DSController.h>
Inherits sc_module.
Public Member Functions
virtual void b_transport (tlm::tlm_generic_payload &trans, sc_time &delay)
~DSController ()
Private Member Functions
void thread_process ()
void make_end ()
void make_Transaction (int addr, int buffer_position)
Private Attributes
sc_int< DATA_WIDTH > instruction
int load
bool search
Detailed Description
Controlador da pilha de dados.
Módulo responsável por determinar quais operandos devem ser carregados da pilha de dados e obter estes operandos da mesma.
Author
Gerson Miguel Beckenkamp
Date
2015/09/05 14:16:20
Definition at line 34 of file DSController.h.
Constructor & Destructor Documentation
DSController::~DSController ()
Destrutor do módulo.
Definition at line 247 of file DSController.cpp.
Member Function Documentation
void DSController::b_transport (tlm::tlm_generic_payload & trans, sc_time & delay) virtual
Socket responsável por receber a instrução carregada pelo Fetch.
Parameters
trans Payload contendo os dados do pacote recebido.
delay Timeout para a condirmação do comando recebido.
Returns
Não há retorno.
Definition at line 28 of file DSController.cpp.
References instruction, load, search, SIZE, and thread_process().
void DSController::make_end () private
Envia uma transação para o módulo Alu com o endereço de buffer 3, forçando assim o fim da transmissão dos operandos.
Returns
Não há retorno.
Definition at line 168 of file DSController.cpp.
Referenced by thread_process().
void DSController::make_Transaction (int addr, int buffer_position) private
Lê o registrador temporal da pilha de dados e envia o operando para o módulo Alu, informando em qual posição do buffer contido na Alu deve ser guardado o operando carregado.
Parameters
addr Endereço do registrador temporal especificado pelo operando.
buffer_position Endereço do buffer contido na Alu onde o dado carregado da pilha será copiado.
Definition at line 202 of file DSController.cpp.
Referenced by thread_process().
void DSController::thread_process () private
Processo responsável por interpretar a instrução e carregar os operandos necessários, que são repassados ao módulo Alu.
Returns
Não há retorno.
Definition at line 68 of file DSController.cpp.
References instruction, load, make_end(), make_Transaction(), and search.
Referenced by b_transport().
Member Data Documentation
sc_int<DATA_WIDTH> DSController::instruction private
Instrução atual.
Definition at line 37 of file DSController.h.
Referenced by b_transport(), and thread_process().
int DSController::load private
Flag utilizada para detectar se há necessidade de buscar operandos.
Definition at line 38 of file DSController.h.
Referenced by b_transport(), and thread_process().
bool DSController::search private
Flag utilizada para controlar a leitura de operandos.
Definition at line 39 of file DSController.h.
Referenced by b_transport(), and thread_process().
The documentation for this class was generated from the following files:
DSController.h
DSController.cpp