StackMachineDualOperand: Fetch Class Reference
Fetch Class Reference
Interface da ROM com o resto do sistema.
#include <Fetch.h>
Inherits sc_module.
Public Member Functions
void setPC (int *pc)
void setCnt (int *cnt)
Private Member Functions
void transaction_Read ()
void transaction_Write ()
void thread_process ()
Thread principal do sistema.
Private Attributes
sc_int< DATA_WIDTH > instruction
int * PC
bool end
int * cntExec
Detailed Description
Interface da ROM com o resto do sistema.
Módulo responsável por controlar o módulo ROM, carregando as instruções e repasando-as para os módulos Alu e DSController.
Author
Gerson Miguel Beckenkamp
Date
2015/09/05 14:16:20
Definition at line 26 of file Fetch.h.
Member Function Documentation
void Fetch::setCnt (int * cnt)
Inicia o contador de ciclos de execução do módulo.
Parameters
cnt Ponteiro para o contador de ciclos de execução.
Returns
Não há retorno.
Definition at line 164 of file Fetch.cpp.
References cntExec.
Referenced by SC_MODULE().
void Fetch::setPC (int * pc)
Inicia o contador de programa do módulo.
Parameters
pc Ponteiro para o contador de programa.
Returns
Não há retorno.
Definition at line 27 of file Fetch.cpp.
References end, and PC.
Referenced by SC_MODULE().
void Fetch::thread_process () private
Thread principal do sistema.
Thread responsável por ler a memória ROM e repassar a instrução carregada para os demais módulos. Também é responsável por detectar o fim de execução.
Returns
Não há retorno.
Definition at line 132 of file Fetch.cpp.
References cntExec, end, PC, transaction_Read(), and transaction_Write().
void Fetch::transaction_Read () private
Utiliza o PC atual como endereço para carregar a nova instrução.
Returns
Não há retorno.
Definition at line 38 of file Fetch.cpp.
References end, instruction, and PC.
Referenced by thread_process().
void Fetch::transaction_Write () private
Repassa a instrução atual para os demais módulos. Também é responsável por detectar o fim de execução.
Returns
Não há retorno.
Definition at line 84 of file Fetch.cpp.
References instruction.
Referenced by thread_process().
Member Data Documentation
int* Fetch::cntExec private
Contador de ciclos de execução.
Definition at line 32 of file Fetch.h.
Referenced by setCnt(), and thread_process().
bool Fetch::end private
Flag utilizada para detectar o fim de execução.
Definition at line 31 of file Fetch.h.
Referenced by setPC(), thread_process(), and transaction_Read().
sc_int<DATA_WIDTH> Fetch::instruction private
Instrução atual.
Definition at line 29 of file Fetch.h.
Referenced by transaction_Read(), and transaction_Write().
int* Fetch::PC private
Contador de programa.
Definition at line 30 of file Fetch.h.
Referenced by setPC(), thread_process(), and transaction_Read().
The documentation for this class was generated from the following files:
Fetch.h
Fetch.cpp