StackMachineDualOperand: Main.cpp File Reference
Main.cpp File Reference
Método main.
#include "systemc"
#include <iostream>
#include "Stack.h"
#include "DataStack.h"
#include "Rom.h"
#include "DSController.h"
#include "Fetch.h"
#include "Alu.h"
#include "Ram.h"
#include "tlm.h"
#include "tlm_utils/simple_initiator_socket.h"
#include "tlm_utils/simple_target_socket.h"
Functions
SC_MODULE (Top)
Detailed Description
Método main.
Author
Gerson Miguel Beckenkamp
Date
2015/09/05 14:16:20
Definition in file Main.cpp.
Function Documentation
SC_MODULE (Top)
Módulo de sistema, contendo todos os demais módulos do projeto, bem como suas ligações.
Definition at line 21 of file Main.cpp.
References Ram::setCnt(), Fetch::setCnt(), Fetch::setPC(), and Alu::setPC().