StackMachineZeroOperand: Alu Class Reference
Alu Class Reference
Unidade Lógico Aritmética.
#include <Alu.h>
Inherits sc_module.
Public Member Functions
void setBuffersDS (int buf[4])
void setBuffersRS (int buf[4])
void setPC (int *pc)
void setDSP (int *dsp)
void setRSP (int *rsp)
void setSizes (int *dss, int *rss)
virtual void b_transport_Fet (tlm::tlm_generic_payload &trans, sc_time &delay)
~Alu ()
Private Member Functions
void compute ()
void writeDS (int adr, int op)
void writeRS (int adr, int op)
void writeRS (int adr, tlm::tlm_command cmd)
void writeDS (int adr, tlm::tlm_command cmd)
void writeRAM (int addr, int op)
int readRAM (int addr)
int pickSource (int op)
void storeSource (int op, int data)
Private Attributes
sc_int< DATA_WIDTH > instruction
int * PC
int * buffersDS
int * buffersRS
int * DSP
int * RSP
int * DSS
int * RSS
Detailed Description
Unidade Lógico Aritmética.
Módulo responsável pela computação dos valores carregados das pilhas e por alocar o resultado na pilha de destino ou em memória.
Author
Gerson Miguel Beckenkamp
Date
2015/09/05 14:16:20
Definition at line 35 of file Alu.h.
Constructor & Destructor Documentation
Alu::~Alu ()
Destrutor do módulo
Definition at line 1430 of file Alu.cpp.
Member Function Documentation
void Alu::b_transport_Fet (tlm::tlm_generic_payload & trans, sc_time & delay) virtual
Socket responsável por receber a instrução carregada pelo Fetch.
Parameters
trans Payload contendo os dados do pacote recebido.
delay Timeout para a condirmação do comando recebido.
Returns
Não há retorno.
Definition at line 92 of file Alu.cpp.
References compute(), instruction, and SIZE.
void Alu::compute () private
Interpreta a instrução atual e realiza as computações necessárias.
Returns
Não há retorno.
Definition at line 127 of file Alu.cpp.
References buffersDS, buffersRS, instruction, PC, pickSource(), readRAM(), storeSource(), writeDS(), writeRAM(), and writeRS().
Referenced by b_transport_Fet().
int Alu::pickSource (int op) private
Retorna o valor contido na origem especificada pelo campo source da instrução.
Parameters
op Campo source da instrução.
Returns
Valor contido na origem especificada.
Definition at line 1241 of file Alu.cpp.
References buffersDS, buffersRS, DSP, DSS, PC, RSP, and RSS.
Referenced by compute().
int Alu::readRAM (int addr) private
Executa a leitura da memória RAM.
Parameters
addr Endereço de memória a ser lido.
Returns
Valor lido no endereço especificado.
Definition at line 1207 of file Alu.cpp.
Referenced by compute().
void Alu::setBuffersDS (int buf[4])
Inicia os buffers da pilha de dados.
Parameters
buff Ponteiro para o array de buffers.
Returns
Não há retorno.
Definition at line 21 of file Alu.cpp.
References buffersDS.
Referenced by SC_MODULE().
void Alu::setBuffersRS (int buf[4])
Inicia os buffers da pilha de retorno.
Parameters
buff Ponteiro para o array de buffers.
Returns
Não há retorno.
Definition at line 43 of file Alu.cpp.
References buffersRS.
Referenced by SC_MODULE().
void Alu::setDSP (int * dsp)
Inicia o endereço de base da pilha de dados na memória.
Parameters
dsp Ponteiro para a base da pilha de dados na memória.
Returns
Não há retorno.
Definition at line 54 of file Alu.cpp.
References DSP.
void Alu::setPC (int * pc)
Inicia o contador de programa do módulo.
Parameters
pc Ponteiro para o contador de programa.
Returns
Não há retorno.
Definition at line 32 of file Alu.cpp.
References PC.
Referenced by SC_MODULE().
void Alu::setRSP (int * rsp)
Inicia o endereço de base da pilha de retorno na memória.
Parameters
rsp Ponteiro para a base da pilha de retorno na memória.
Returns
Não há retorno.
Definition at line 65 of file Alu.cpp.
References RSP.
void Alu::setSizes (int * dss, int * rss)
Inicia os endereços de topo das pilhas de dados e retorno na memória.
Parameters
dss Ponteiro para o topo da pilha de dados na memória.
rss Ponteiro para o topo da pilha de retorno na memória.
Returns
Não há retorno.
Definition at line 78 of file Alu.cpp.
References DSS, and RSS.
void Alu::storeSource (int op, int data) private
Guarda o dado computado no destino especificado no campo destination da instrução.
Parameters
op Campo destination da instrução.
data Dado a ser armazenado no destino.
Returns
Valor contido na origem especificada.
Definition at line 1335 of file Alu.cpp.
References DSP, PC, RSP, writeDS(), and writeRS().
Referenced by compute().
void Alu::writeDS (int adr, int op) private
Executa uma escrita da pilha de dados.
Parameters
adr Posição da pilha a ser escrita.
op Dado a ser escrito.
Returns
Não há retorno.
Definition at line 1041 of file Alu.cpp.
Referenced by compute(), and storeSource().
void Alu::writeDS (int adr, tlm::tlm_command cmd) private
Executa uma escrita da pilha de dados.
Parameters
adr Tipo de modulação.
cmd Comando identificando uma modulação. Padrão = TLM_IGNORE_COMMAND.
Returns
Não há retorno.
Definition at line 1142 of file Alu.cpp.
void Alu::writeRAM (int addr, int op) private
Executa a escrita de um dado na memória RAM.
Parameters
addr Endereço de memória a ser escrito.
op Dado a ser escrito.
Returns
Não há retorno.
Definition at line 1175 of file Alu.cpp.
Referenced by compute().
void Alu::writeRS (int adr, int op) private
Executa uma escrita no topo pilha de retorno.
Parameters
adr Posição da pilha a ser escrita.
op Dado a ser guardado.
Returns
Não há retorno.
Definition at line 1075 of file Alu.cpp.
Referenced by compute(), and storeSource().
void Alu::writeRS (int adr, tlm::tlm_command cmd) private
Executa uma modulação no topo da pilha de retorno.
Parameters
adr Tipo de modulação.
cmd Comando identificando uma modulação. Padrão = TLM_IGNORE_COMMAND.
Returns
Não há retorno.
Definition at line 1109 of file Alu.cpp.
Member Data Documentation
int* Alu::buffersDS private
Buffer contendo as 4 posições mais ao topo da pilha de dados.
Definition at line 40 of file Alu.h.
Referenced by compute(), pickSource(), and setBuffersDS().
int* Alu::buffersRS private
Buffer contendo as 4 posições mais ao topo da pilha de retorno.
Definition at line 41 of file Alu.h.
Referenced by compute(), pickSource(), and setBuffersRS().
int* Alu::DSP private
Ponteiro para o endereço da base das pilha de dados na RAM.
Definition at line 42 of file Alu.h.
Referenced by pickSource(), setDSP(), and storeSource().
int* Alu::DSS private
Ponteiro para a última posição atualizada do topo da pilhas de dados.
Definition at line 44 of file Alu.h.
Referenced by pickSource(), and setSizes().
sc_int<DATA_WIDTH> Alu::instruction private
Instrução atual.
Definition at line 38 of file Alu.h.
Referenced by b_transport_Fet(), and compute().
int* Alu::PC private
Contador de programa.
Definition at line 39 of file Alu.h.
Referenced by compute(), pickSource(), setPC(), and storeSource().
int* Alu::RSP private
Ponteiro para o endereço da base das pilha de retorno na RAM.
Definition at line 43 of file Alu.h.
Referenced by pickSource(), setRSP(), and storeSource().
int* Alu::RSS private
Ponteiro para a última posição atualizada do topo da retorno na memória.
Definition at line 45 of file Alu.h.
Referenced by pickSource(), and setSizes().
The documentation for this class was generated from the following files:
Alu.h
Alu.cpp