StackMachineZeroOperand: Stack Class Reference
Stack Class Reference
Pilha de retorno.
#include <ReturnStack.h>
Inherits sc_module.
Public Member Functions
void setBuffers (int *buf)
~Stack ()
Private Member Functions
virtual void b_transport (tlm::tlm_generic_payload &trans, sc_time &delay)
void updateBuffers ()
Detailed Description
Pilha de retorno.
Módulo responsável por manter e fazer a interface da pilha de retorno com os demais blocos.
Author
Gerson Miguel Beckenkamp
Date
2015/09/05 14:16:20
Definition at line 33 of file ReturnStack.h.
Constructor & Destructor Documentation
Stack::~Stack ()
Destrudor do módulo.
Definition at line 131 of file ReturnStack.cpp.
Member Function Documentation
void Stack::b_transport (tlm::tlm_generic_payload & trans, sc_time & delay) private virtual
Socket responsável por receber requisições oriundas da Alu.
Parameters
trans Payload contendo os dados do pacote recebido.
delay Timeout para a condirmação do comando recebido.
Returns
Não há retorno.
Definition at line 26 of file ReturnStack.cpp.
References DS_SIZE, SIZE, and updateBuffers().
void Stack::setBuffers (int * buf)
Inicia os buffers de topo de pilha.
Returns
Não há retorno.
Definition at line 124 of file ReturnStack.cpp.
Referenced by SC_MODULE().
void Stack::updateBuffers () private
Executa a sincronização dos buffers com o topo da pilha.
Returns
Não há retorno.
Definition at line 109 of file ReturnStack.cpp.
Referenced by b_transport().
The documentation for this class was generated from the following files:
ReturnStack.h
ReturnStack.cpp